package com.carpool.tagalong.constants;

public class Constants {
    public static final String USERNAME = "userName";
    public static final String EMAIL = "email";
    public static final String MOBILENO = "mobileNo";
    public static final String ADDRESS =  "address";
    public static final String PASSWORD = "password" ;
    public static final String REPASSWORD = "rePassword";
    public static final String MY_PREF = "TAGALONG" ;
    public static final String TOKEN =     "token";
    public static final String TYPE_DOCUMENT = "2";
    public static final String PROFILE_PIC = "1";
    public static final String START_RIDE = "start";
    public static final String END_RIDE ="end" ;
    public static final String STARTLOCATION = "startlocation" ;
    public static final String DATETIME = "datetime";
    public static final String STRIPE_KEY_DEBUG = "pk_test_Mra4jDjZGMnUowxMBn9mW6xD00Gv44Zf4i";
    public static final int PENDING = 1;
    public static final int ACCEPTED = 3;
    public static final int REQUESTED = 2;
    public static final int PICKUP = 4;
    public static final int DROP = 5;
    public static final int OWN_CANCELLED = 6;
    public static final String DEVICE_TOKEN = "device_token";
    public static final String DEVICE_TOKEN_STRING = "deviceToken";
    public static final String DEVICE_TYPE_STRING = "deviceType";
    public static final String DEVICE_TYPE = "2";
    public static final int IMAGE_FILTER_CODE = 645;
    public static final String TYPE_IMAGE = "1";
    public static final int DRIVER_PENDING = 11;
    public static final int DRIVER_SCHEDULED = 12;
    public static final int STARTED = 13;
    public static final int COMPLETED = 14;
    public static final int DRIVER_CANCELLED = 15;
    public static final String DRIVER_DATA = "driver_data";
    public static final int INVITE_GUEST_REQUEST_CODE = 007 ;
    public static final String DEFAULT_CARD = "defaultCard";
    public static final String CARD = "card";
    public static final String RIDE_DETAIL = "ride_detail";
    public static final String IFRAME_MODE = "iframe";

    public static final String TYPE_RIDES = "1";
    public static final String TYPE_ALERT = "2";
    public static final String TYPE_CHAT  = "3";
    public static final String TYPE_PANIC_BUTTON = "5";
    public static final String TYPE_PICKUP = "6";
    public static final String TYPE_DROP   = "7";
    public static final String TYPE_QUICKRIDE = "8";
    public static final String TYPE_RIDE_CANCELLED_BY_PASSENGER = "4";

    public static final String PICKED_UP = "pickedup";
    public static final String DROPPED = "dropped";
    public static final String RIDEID = "rideId";
    public static final String FROM = "from";
    public static final String SIGNUP = "signup";
    public static final String CURRENTUPCOMING = "current_upcoming";
    public static final String RIDELISTENER = "ride_listener";
    public static final String SENDER = "sender";
    public static final String RECEIVERID = "receiverId";
    public static final String CHAT_MESSAGE = "chatMessage";
    public static final String LAUNCH_CURRENT_RIDE_FRAGMENT = "launchCurrentRideFragment";
    public static final String SINCH_KEY = "b36d023d-4349-463a-a1ba-ad07fb7675d9";
    public static final String SINCH_SECRET = "SBbKAwHqjEq1EK/7QdJI5w==";
}